import "~/styles/globals.css";
import TopNav from "./_components/TopNav";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'


export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by Abhishek wali",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable}`}>
      <body>
        
        <div className="w-full flex flex-col gap-4">
          <TopNav />
          
          First layout
          {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
