import "~/styles/globals.css";
import TopNav from "./_components/TopNav";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import "@uploadthing/react/styles.css";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by Abhishek wali",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // function extractRouterConfig(ourFileRouter: any) {
  //   throw new Error("Function not implemented.");
  // }

  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable}`}>
     
      <body>
          
        
        <div className="w-full flex flex-col gap-4">

          <TopNav />
                <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        
          {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
